# Generated by Django 4.2 on 2024-04-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patient",
            name="email",
            field=models.EmailField(max_length=200),
        ),
    ]
