# Generated by Django 4.2 on 2024-04-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_app", "0002_patient_is_active_alter_patient_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
