# Generated by Django 4.2 on 2024-04-11 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("care_app", "0003_patient_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Acetaminophen", "Adderall"),
                            ("Amitriptyline", "Amoxicillin"),
                            ("Ativan", "Atorvastatin"),
                            ("Azithromycin", "Benzonatate"),
                            ("Brilinta", "Bunavail"),
                            ("Buprenophine", "Cephalexin"),
                            ("Ciprofloxacin", "Citalopram"),
                            ("Clindamycin", "Clonazepam"),
                            ("Cyclobenzaprine", "Cymbalta"),
                            ("Doxycycline", "Dupixent"),
                            ("Entresto", "Entyvio"),
                            ("Farxiga", "Fentanyl"),
                        ],
                        max_length=200,
                        verbose_name="Medication Name",
                    ),
                ),
                ("dosage", models.IntegerField(verbose_name="Dosage")),
                (
                    "takenDaily",
                    models.BooleanField(default=False, verbose_name="Taken Daily?"),
                ),
                ("startDate", models.DateField(verbose_name="Starting Date")),
                ("endDate", models.DateField(verbose_name="Ending Date")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="care_app.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medications",
            },
        ),
    ]
