# Generated by Django 4.2 on 2024-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care_app", "0004_medication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="name",
            field=models.CharField(
                choices=[
                    ("Acetaminophen", "Acetaminophen"),
                    ("Adderall", "Adderall"),
                    ("Amitriptyline", "Amitriptyline"),
                    ("Amlodipine", "Amlodipine"),
                    ("Amoxicillin", "Amoxicillin"),
                    ("Ativan", "Ativan"),
                    ("Atorvastatin", "Atorvastatin"),
                    ("Azithromycin", "Azithromycin"),
                    ("Benzonatate", "Benzonatate"),
                    ("Brilinta", "Brilinta"),
                    ("Bunavail", "Bunavail"),
                    ("Buprenophine", "Buprenophine"),
                    ("Cephalexin", "Cephalexin"),
                    ("Ciprofloxacin", "Ciprofloxacin"),
                    ("Citalopram", "Citalopram"),
                    ("Clindamycin", "Clindamycin"),
                    ("Clonazepam", "Clonazepam"),
                    ("Cyclobenzaprine", "Cyclobenzaprine"),
                    ("Cymbalta", "Cymbalta"),
                    ("Doxycycline", "Doxycycline"),
                    ("Dupixent", "Dupixent"),
                    ("Entresto", "Entresto"),
                    ("Entyvio", "Entyvio"),
                    ("Farxiga", "Farxiga"),
                    ("Fentaynl", "Fentanyl"),
                    ("Gabapentin", "Gabapentin"),
                    ("Gilenya", "Gilenya"),
                    ("Humira", "Humira"),
                    ("Hydrochlorothiazide", "Hydrochlorothiazide"),
                    ("Ibuprofen", "Ibuprofen"),
                    ("Imbruvica", "Imbruvica"),
                    ("Januvia", "Januvia"),
                    ("Kevzara", "Kevzara"),
                    ("Leqvio", "Leqvio"),
                    ("Lexapro", "Lexapro"),
                    ("Lisinopril", "Lisinopril"),
                    ("Lyrica", "Lyrica"),
                    ("Melatonin", "Melatonin"),
                    ("Meloxicam", "Meloxicam"),
                    ("Metformin", "Metformin"),
                    ("Methadone", "Methadone"),
                    ("Metoprolol", "Metoprolol"),
                    ("Naloxone", "Narcan"),
                    ("Nurtec", "Nurtec"),
                ],
                max_length=200,
                verbose_name="Medication Name",
            ),
        ),
    ]
