# Generated by Django 4.2 on 2024-04-20 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("care_app", "0007_registereduser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="registeredUser",
        ),
    ]
